bestfilm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('films.urls')),
    path('users/', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

films/urls.py
from django.urls import path

from . import views

app_name = 'films'
urlpatterns = [
    #Головна сторінка
    path('', views.index, name='index'),

    #Сторінка з детальнішим описом фільмів
    path('more', views.more, name='more'),

    #Сторінка з детальнішим описом фільмів
    path('film/<int:film_id>', views.film, name='film'),

    #Сторінка для додавання тега
    path('new_tag', views.new_tag, name='new_tag'),

    #Сторінка для додавання фільму
    path('new_film', views.new_film, name='new_film'),

    #Додавання лайку до коментаря
    path('film/<int:film_id>/<int:comment_id>/<int:user_id>', views.add_like, name='add_like'),

    #Сторінка рандомного фільму
    path('film/', views.random_film, name='random_film'),

    #Сторінка блогу
    path('blog/', views.blog, name='blog'),


]

users/urls.py
from django.urls import path, include

from . import views

app_name = 'users'

urlpatterns = [
    #Автентифікація
    path('', include('django.contrib.auth.urls')),

    #Реєстрація
    path('register/', views.register, name='register'),

    #Сторінка користувача
    path('account/<int:user_id>/', views.account, name='account'),

    #Лайкнути пост на сторінці
    path('account/<int:user_id>/<int:post_id>/', views.add_acc_like, name='acclike'),

    #Поділитись постом
    path('share/<int:post_id>/<int:user_id>/', views.share, name='share'),

    #Написати пост на сторінці
    path('account/add_post/<int:user_id>/', views.create_page_post, name='create_page_post'),

    #Сторінка з повідомленнями
    path('account/messages/<int:user_id>/<int:default_id>/', views.show_messages, name='show_messages'),

    #Позначити повідомлення як прочитане
    path('account/messages/readed/<int:user_id>/<int:message_id>/', views.mark_as_read, name='mark_as_read'),

    #Видалити повідомлення
    path('account/messages/delete/<int:user_id>/<int:message_id>/', views.delete_message, name='delete_message'),

    #Відстежувати профіль користувача
    path('account/save/<int:to_save_id>/<int:saver_id>/', views.save_acc, name='save_acc'),

    #Профілі, що відстежуються
    path('account/saved_profiles/<int:user_id>/', views.saved_accs, name='saved_accs'),

    #Редагувати профіль
    path('account/<int:user_id>/edit/', views.edit_acc, name='edit_acc'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

def default_post_list():
    return dict(id = [], saved_accs=[])

def default_list_of_likers():
    return dict(liked = [], saved = [])

def default_messages():
    return dict(unseen = [], seen =[], send = [])

class CustomUser(AbstractUser):
    """Кастомний користувач"""
    status = models.CharField(max_length=100, default='---', verbose_name='Статус')
    dob = models.DateField(blank=True, null=True, default='1999-12-31', verbose_name='Дата народження')
    about = models.TextField(blank=True, null=True, default='---', verbose_name='Про себе')
    image = models.ImageField(upload_to='images/avatars', blank=True, null=True, verbose_name='Аватар')
    post_list = models.JSONField(blank=True, null=True, default=default_post_list, verbose_name='Список постів')


class PagePost(models.Model):
    """Запис на власній сторінці"""
    title = models.CharField(max_length=20, verbose_name='Заголовок')
    image = models.ImageField(blank=True, null=True, upload_to='images/post_images', verbose_name='Зображення')
    text = models.TextField(blank=True, null=True, verbose_name='Текст')
    likes = models.IntegerField(default=0, verbose_name='К-ть лайків')
    list_of_likers = models.JSONField(blank=True, null=True, default=default_list_of_likers, verbose_name='Хто лайкнув')
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE, default=CustomUser.objects.get(id=1).id, verbose_name='Автор')
    date_added = models.DateTimeField(auto_now_add=True, blank=True, null=True, verbose_name='Дата додання')

    def __str__(self):
        return self.title

    def like(self):
        """Лайкнути пост"""
        self.likes += 1
        self.save()

    def unlike(self):
        """Забрати лайк з поста"""
        self.likes -= 1
        self.save()


class Inbox(models.Model):
    """Поштова скринька. Для повідомлень, наприклад"""
    messages = models.JSONField(blank=True, null=True, default=default_messages, verbose_name='Повідомлення')
    customuser = models.OneToOneField('CustomUser', on_delete=models.CASCADE, verbose_name='Кому належить')

    def __str__(self):
        return f"{self.customuser.username} inbox"


class Message(models.Model):
    """Повідомлення (як СМС)"""
    text = models.TextField()
    author = models.ForeignKey(CustomUser, verbose_name='Автор', related_name='author', on_delete=models.CASCADE, default=CustomUser.objects.get(id=1).id)
    receiver = models.ForeignKey(CustomUser, verbose_name='Отримувач', related_name='receiver', on_delete=models.CASCADE, default=CustomUser.objects.get(id=1).id)
    time = models.DateTimeField(auto_now_add=True, verbose_name='Час надсилання')

    def __str__(self):
        return self.text[:10]

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms

from .models import *


class RegisterForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ["username", "password1", "password2", "dob", "email", "status", "about"]


class PagePostForm(forms.ModelForm):
    """Створити допис на сторінці"""
    def __init__(self, *args, **kwargs):
        user_id = kwargs.pop('user_id')
        super().__init__(*args, **kwargs)
        self.fields['author'].initial = CustomUser.objects.get(id=user_id)

    class Meta:
        model = PagePost
        fields = ["title", "image", "text", "author"]
        widgets = {
            'author': forms.TextInput(attrs={'type': 'hidden'}),
            }


class MessageForm(forms.ModelForm):
    """Форма для написання повідомлення"""
    def __init__(self, *args, **kwargs):
        user_id = kwargs.pop('user_id')
        receiver_id = kwargs.pop('receiver_id')
        super().__init__(*args, **kwargs)
        self.fields['author'].initial = CustomUser.objects.get(id=user_id)
        self.fields['receiver'].initial = CustomUser.objects.get(id=receiver_id)
    class Meta:
        model = Message
        fields = ["text", "author", "receiver"]
        widgets = {
            'author': forms.TextInput(attrs={'type': 'hidden'}),
            'text': forms.Textarea(attrs={'cols': 50, 'rows': 10}),
        }


class SearchUserForm(forms.Form):
    """Форма для вводу імені користувача і пошуку за іменем"""
    username = forms.CharField(max_length=100, label='UsernameInput', required=False)

users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect


from .forms import *
from .models import *

def register(request):
    """Реєстрація користувача"""
    if request.method != 'POST':
        form = RegisterForm()
    else:
        form = RegisterForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('films:index')
    context = {'form': form}
    return render(request, 'registration/register.html', context)


@login_required
def account(request, user_id):
    """Сторінка користувача за ід"""
    user = get_object_or_404(CustomUser, id=user_id)
    inbox = Inbox.objects.filter(customuser=user_id)
    if not inbox:
        new_inbox = Inbox(customuser=user)
        new_inbox.save()
        inbox = Inbox.objects.filter(customuser=user_id)

    user_posts = []
    new_messages_count = len(inbox[0].messages['unseen'])

    user_posts = []
    test_post = PagePost.objects.filter(id=1)
    if user.post_list:
        for id in user.post_list['id']:
            exact_post = PagePost.objects.filter(id=id)
            if exact_post:
                user_posts.insert(0, exact_post)



    context = {
        'accuser': user,
        'user_posts': user_posts,
        'inbox': inbox,
        'new_messages_count': new_messages_count
    }
    return render(request, 'users/account.html', context)


@login_required
def add_acc_like(request, user_id, post_id):
    """Додати лайк"""
    post = get_object_or_404(PagePost, id=post_id)
    if int(user_id) not in post.list_of_likers['liked']:
        post.list_of_likers['liked'].append(user_id)
        post.like()
    else:
        post.list_of_likers['liked'].remove(user_id)
        post.unlike()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', 'films:index'))


@login_required
def share(request, post_id, user_id):
    """Поділитись дописом"""
    post = get_object_or_404(PagePost, id=post_id)
    user = get_object_or_404(CustomUser, id=user_id)
    liked_list = post.list_of_likers['saved']
    saved_list = user.post_list['id']

    if int(user_id) not in liked_list:
        liked_list.append(user_id)
        post.save()

    if int(post_id) not in saved_list:
        saved_list.append(post_id)
        user.save()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', 'films:index'))


@login_required
def create_page_post(request, user_id):
    """Створити допис на сторінці"""
    user = get_object_or_404(CustomUser, id=user_id)
    if request.method == 'GET':
        form = PagePostForm(user_id=user_id)
    else:
        form = PagePostForm(request.POST, request.FILES, user_id=user_id)
        if form.is_valid():
            new_form = form.save()
            user.post_list['id'].append(new_form.id)
            user.save()
            return redirect('films:index')
    context = {
        'form': form
    }
    return render(request, 'users/add_acc_post.html', context)


@login_required
def show_messages(request, user_id, default_id):
    """Показати повідомлення"""
    accuser = get_object_or_404(CustomUser, id=user_id)
    inbox = get_object_or_404(Inbox, customuser=user_id)
    unseen_messages = []
    seen_messages = []
    sent_messages = []

    for id in inbox.messages['unseen']:
        exact_message = Message.objects.filter(id=id)
        if exact_message:
            unseen_messages.insert(0, exact_message)

    for id in inbox.messages['seen']:
        exact_message = Message.objects.filter(id=id)
        if exact_message:
            seen_messages.insert(0, exact_message)

    for id in inbox.messages['send']:
        exact_message = Message.objects.filter(id=id)
        if exact_message:
            sent_messages.insert(0, exact_message)

    if request.method == 'GET':
        form = MessageForm(user_id=user_id, receiver_id=default_id)
    else:
        form = MessageForm(request.POST, user_id=user_id, receiver_id=default_id)
        if form.is_valid():
            new_message = form.save()
            inbox.messages['send'].append(new_message.id)
            receiver_inbox = Inbox.objects.get(id=request.POST['receiver'])
            receiver_inbox.messages['unseen'].append(new_message.id)
            inbox.save()
            receiver_inbox.save()
            return HttpResponseRedirect(request.META.get('HTTP_REFERER', 'films:index'))



    context = {
        'accuser': accuser,
        'inbox': inbox,
        'unseen_messages': unseen_messages,
        'seen_messages': seen_messages,
        'sent_messages': sent_messages,
        'form': form
    }
    return render(request, 'users/messages.html', context)


@login_required
def mark_as_read(request, user_id, message_id):
    """Позначити повідомлення як прочитане"""
    message = get_object_or_404(Message, id=message_id)
    user = get_object_or_404(CustomUser, id=user_id)
    inbox = get_object_or_404(Inbox, customuser=user)
    inbox.messages['unseen'].remove(message_id)
    inbox.messages['seen'].append(message_id)
    inbox.save()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', 'films:index'))


@login_required
def delete_message(request, user_id, message_id):
    """Видалити повідомлення"""
    message = get_object_or_404(Message, id=message_id)
    user = get_object_or_404(CustomUser, id=user_id)
    inbox = get_object_or_404(Inbox, customuser=user)

    for cat in inbox.messages:
        if int(message_id) in inbox.messages[cat]:
            print(cat)
            inbox.messages[cat].remove(message_id)
    inbox.save()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', 'films:index'))


@login_required
def save_acc(request, to_save_id, saver_id):
    """Відстежувати профіль користувача"""
    saver = get_object_or_404(CustomUser, id=saver_id)
    if int(to_save_id) not in saver.post_list['saved_accs']:
        saver.post_list['saved_accs'].append(to_save_id)
        saver.save()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', 'films:index'))


@login_required
def saved_accs(request, user_id):
    """Список профілів, що відстежуються користувачем"""
    accuser = get_object_or_404(CustomUser, id=user_id)
    profile_list = accuser.post_list['saved_accs']
    profiles = []
    for p in profile_list:
        profiles.append(CustomUser.objects.filter(id=p)[0])

    users = None
    if request.method == 'POST':
        form = SearchUserForm(request.POST)
        if form.is_valid():
            users = find_user(form.cleaned_data['username'])
    else:
        form = SearchUserForm()


    context = {
        'accuser': accuser,
        'profiles': profiles,
        'form': form,
        'users': users
    }
    return render(request, 'users/saved_accs.html', context)


def find_user(username):
    """Пошук користувача за іменем"""
    if username == '':
        return CustomUser.objects.filter(id=1)
    list_of_users = CustomUser.objects.filter(username__icontains=username)
    return list_of_users


def edit_acc(request, user_id):
    """Редагувати профіль"""
    pass

users/templates/users/account.html
{% extends 'films/base.html' %}
{% load static %}
{% load films_extras %}

{% block head %}
    <title>{{ accuser.username }}</title>
{% endblock head %}

{% block content %}
<style>
.like-button{
    background:  url('{% static 'films/img/like_hollow.png' %}');
    background-size: contain;
    background-repeat: no-repeat;
    width: 50px;
    height: 50px;
    background-color: transparent;
    border-color: transparent;
}


.liked:hover{
    background:  url('{% static 'films/img/like_hollow.png' %}');
    background-size: contain;
    background-repeat: no-repeat;
    cursor: pointer;
}


.unliked:hover{
    background:  url('{% static 'films/img/like.png' %}');
    background-size: contain;
    background-repeat: no-repeat;
    cursor: pointer;
}


.liked{
    background:  url('{% static 'films/img/like.png' %}');
    background-size: contain;
    background-repeat: no-repeat;
}


.unliked
    background:  url('{% static 'films/img/like_hollow.png' %}');
    background-size: contain;
    background-repeat: no-repeat;
}

#message-icon{
    background:  url('{% static 'films/img/message_logo.png' %}');
    background-size: contain;
    background-repeat: no-repeat;
    width: 35px;
    height: 35px;
    text-align: center;
}

</style>

    <div class="account-content">
        <table>
            <tr>
                <td>
                    {% if accuser.image %}
                        <img id="account-avatar" src="{{ accuser.image.url }}">
                    {% else %}
                        <img id="account-avatar" src="{% static 'films/img/anon_image.png' %}">
                    {% endif %}
                    <div id="name" align="center"><b><i>{{ accuser.username }}</i></b></div>
                </td>
                <td width="100%">
                    <div id="status">
                        <b>Улюблена цитата:</b> <p><i>{{ accuser.status }}</i></p>
                        <b>Про себе:</b> <p><i>{{ accuser.about }}</i></p>
                        <b>Дата народження:</b> <p><i>{{ accuser.dob|date:'d M Y' }}</i></p>
                    </div>

                </td>
            </tr>
            <tr>


            </tr>
        </table>

    </div>

    <div class="my-posts">

        {% if accuser.id == user.id %}
            <div class="account-content">
                <table>
                    <tr>
                        <td>&nbsp;</td>
                        <td><a href="{% url 'users:show_messages' user.id 1 %}">Мої повідомлення</a></td>
                        {% if new_messages_count %}
                            <td>
                                <div id="message-icon">
                                    <span id="message-count">{{ new_messages_count }}</span>
                                </div>
                            </td>
                        {% endif %}
                        <td>&nbsp;</td>
                        <td><a href="{% url 'users:saved_accs' user.id %}">Збережені профілі</a></td>
                    </tr>
                </table>
            </div>
        {% else %}
            <div class="account-content">
                <table>
                    <tr>
                        <td>
                            <form action="{% url 'users:save_acc' accuser.id user.id %}">
                                <button>Відстежувати цей профіль</button>
                            </form>
                        </td>
                        <td>&nbsp;</td>
                        <td>
                            <form action="{% url 'users:show_messages' user.id accuser.id %}">
                                <button>Надіслати повідомлення</button>
                            </form>
                        </td>
                    </tr>
                </table>
            </div>
        {% endif %}

        {% if accuser.id == user.id %}
            <h1 align="center">Мої дописи <a href="{% url 'users:create_page_post' user.id %}"><button>+</button></a></h1>

        {% else %}
            <h1 align="center">Дописи {{ accuser.username }}</h1>
        {% endif %}
        <ul class="no-bullets">
            {% for post in user_posts %}
            <li>
                <div class="post-on-page">
                    <div class="inner-content">
                        {% for p in post %}
                            <h2 align="center">{{ p.title }}</h2>
                            <p>{{ p.text }}</p>
                            <p align="center"><img id="post-image" src="{{ p.image.url }}"></p>
                            <table id="post-info">
                                <tr>
                                    <td align="left">
                                        <a id="author-href" href="{% url 'users:account' p.author.id %}">{{ p.author.username }}</a> --- {{ p.date_added|date:'d M Y' }}
                                    </td>
                                    <td align="right">
                                        <form action="{% url 'users:acclike' accuser.id p.id %}">
                                            <button formaction="{% url 'users:share' p.id user.id %}">Поділитись</button>
                                            {% if p.list_of_likers.liked|check_if_liked:user.id %}
                                                <button align="right" class="like-button liked"></button>
                                            {% else %}
                                                <button align="right" class="like-button unliked"></button>
                                            {% endif %}
                                            {{ p.likes }}
                                        </form>
                                    </td>
                                    <td>Liked - {{ p.list_of_likers.liked }}</td>
                                    <td>Saved - {{ p.list_of_likers.saved }}</td>
                                </tr>

                            </table>
                        {% endfor %}
                    </div>
                </div>
            </li>
            {% endfor %}
        </ul>

    </div>

{% endblock content %}

users/templates/users/add_acc_post.html
{% extends 'films/base.html' %}

{% block content %}
    <form action="{% url 'users:create_page_post' user.id %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Опублікувати</button>
    </form>
{% endblock content %}

users/templates/users/saved_accs.html
{% extends 'films/base.html' %}
{% load static %}

{% block head %}
    <title>Збережені профілі</title>
{% endblock head %}


{% block content %}
    <div class="search">
        <h2>Знайти користувача</h2>
        <form action="{% url 'users:saved_accs' user.id %}" method="post">
            {% csrf_token %}
            {{ form.username }}
            <button name="submit">Пошук</button>
        </form>
    </div>
    <div class="search search-results">
        <table class="results-table">
            {% if users %}
                <tr>
                    <td><b>Аватар</b></td><td><b>Ім'я</b></td><td><b>Id</b></td>
                </tr>
            {% endif %}
            {% for u in users %}
                <tr>
                    {% if u.image %}
                        <td><a href="{% url 'users:account' u.id %}"><img class="avatar" src="{{ u.image.url }}"></a></td>
                    {% else %}
                        <td><a href="{% url 'users:account' u.id %}"><img class="avatar" src="{% static 'films/img/anon_image.png' %}"></a></td>
                    {% endif %}
                    <td><a href="{% url 'users:account' u.id %}">{{ u.username }}</a></td>
                    <td>{{ u.id }}</td>
                </tr>
                <tr>
                    <td><hr></td><td><hr></td><td><hr></td><td><hr></td><td><hr></td>
                </tr>
            {% endfor %}
        </table>



    </div>

    <div class="post-on-page simple-shadow mg-t-3">
        <h2 align="center">Збережені профілі</h2>
        <table class="acc-list-table">
            <tr>
                <td><b>Аватар</b></td>
                <td><b>Ім'я</b></td>
                <td><b>Дата народження</b></td>
                <td>&nbsp;</td>
            </tr>
            <tr>
                <td><hr></td><td><hr></td><td><hr></td><td><hr></td>
            </tr>
            {% for profile in profiles %}
                {% if profile.image %}
                    <tr>
                        <td><a href="{% url 'users:account' profile.id %}"><img class="avatar" src="{{ profile.image.url }}"></a></td>
                        <td><a href="{% url 'users:account' profile.id %}">{{ profile.username }}</a></td>
                        <td>{{ profile.dob }}</td>
                        <td>
                            <form action="{% url 'users:show_messages' user.id profile.id %}">
                                <button>Надіслати повідомлення</button>
                            </form>
                        </td>
                    </tr>
                    <tr>
                        <td><hr></td><td><hr></td><td><hr></td><td><hr></td>
                    </tr>
                {% else %}
                    <tr>
                        <td><a href="{% url 'users:account' profile.id %}"><img class="avatar" src="{% static 'films/img/anon_image.png' %}"></a></td>
                        <td><a href="{% url 'users:account' profile.id %}">{{ profile.username }}</a></td>
                        <td>{{ profile.dob }}</td>
                        <td>
                            <form action="{% url 'users:show_messages' user.id profile.id %}">
                                <button>Надіслати повідомлення</button>
                            </form>
                        </td>
                    </tr>
                    <tr>
                        <td><hr></td><td><hr></td><td><hr></td><td><hr></td>
                    </tr>
                {% endif %}
            {% endfor %}
        </table>




    </div>
{% endblock content %}