bestfilm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('films.urls')),
    path('users/', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

films/urls.py
from django.urls import path

from . import views

app_name = 'films'
urlpatterns = [
    #Головна сторінка
    path('', views.index, name='index'),

    #Сторінка з детальнішим описом фільмів
    path('more', views.more, name='more'),

    #Сторінка з детальнішим описом фільмів
    path('film/<int:film_id>', views.film, name='film'),

    #Сторінка для додавання тега
    path('new_tag', views.new_tag, name='new_tag'),

    #Сторінка для додавання фільму
    path('new_film', views.new_film, name='new_film'),

    #Додавання лайку до коментаря
    path('film/<int:film_id>/<int:comment_id>/<int:user_id>', views.add_like, name='add_like'),

    #Сторінка рандомного фільму
    path('film/', views.random_film, name='random_film'),

    #Сторінка блогу
    path('blog/', views.blog, name='blog'),


]

users/urls.py
from django.urls import path, include

from . import views

app_name = 'users'

urlpatterns = [
    #Автентифікація
    path('', include('django.contrib.auth.urls')),

    #Реєстрація
    path('register/', views.register, name='register'),

    #Сторінка користувача
    path('account/<int:user_id>/', views.account, name='account'),

    #Лайкнути пост на сторінці
    path('account/<int:user_id>/<int:post_id>/', views.add_acc_like, name='acclike'),

    #Поділитись постом
    path('share/<int:post_id>/<int:user_id>/', views.share, name='share'),

    #Написати пост на сторінці
    path('account/add_post/<int:user_id>/', views.create_page_post, name='create_page_post'),

    #Сторінка з повідомленнями
    path('account/messages/<int:user_id>/<int:default_id>/', views.show_messages, name='show_messages'),

    #Позначити повідомлення як прочитане
    path('account/messages/readed/<int:user_id>/<int:message_id>/', views.mark_as_read, name='mark_as_read'),

    #Видалити повідомлення
    path('account/messages/delete/<int:user_id>/<int:message_id>/', views.delete_message, name='delete_message'),

    #Відстежувати профіль користувача
    path('account/save/<int:to_save_id>/<int:saver_id>/', views.save_acc, name='save_acc'),

    #Профілі, що відстежуються
    path('account/saved_profiles/<int:user_id>/', views.saved_accs, name='saved_accs'),

    #Редагувати профіль
    path('account/<int:user_id>/edit/', views.edit_acc, name='edit_acc'),
]

films/models.py
from django.db import models

from users.models import CustomUser

def default_list_of_likers():
    return dict(liked = [])

class Film(models.Model):
    """Фільм"""
    title = models.CharField(max_length = 100, verbose_name='Назва')
    image = models.ImageField(upload_to='images', verbose_name='Постер')
    text = models.TextField(verbose_name='Опис')
    duration = models.IntegerField(verbose_name='Тривалість у хв')
    url = models.URLField(verbose_name='Посилання на трейлер')
    country = models.ForeignKey('Tag', related_name='country', on_delete=models.PROTECT, verbose_name='Країна')
    tag1 = models.ForeignKey('Tag', related_name='tag1', on_delete=models.PROTECT, blank=True, null=True, verbose_name='Тег 1')
    tag2 = models.ForeignKey('Tag', related_name='tag2', on_delete=models.PROTECT, blank=True, null=True, verbose_name='Тег 2')

    def __str__(self):
        return self.title


class Tag(models.Model):
    """Тег"""
    title = models.CharField(max_length = 20, verbose_name='Назва тегу')

    def __str__(self):
        return self.title


class Comment(models.Model):
    """Коментар до фільму"""
    film = models.ForeignKey('Film', on_delete=models.PROTECT, verbose_name='Фільм')
    title = models.CharField(max_length = 30, verbose_name='Заголовок')
    text = models.TextField(verbose_name='Текст')
    likes = models.IntegerField(default=0, verbose_name='К-ть лайків')
    date_added = models.DateTimeField(auto_now_add=True, verbose_name='Дата додання')
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE, default=CustomUser.objects.get(id=1).id, verbose_name='Автор')
    list_of_likers = models.JSONField(blank=True, null=True, default=default_list_of_likers, verbose_name='Хто лайкнув')

    def __str__(self):
        return self.title

    def like(self):
        """Збільшити к-ть лайків на 1"""
        self.likes += 1
        self.save()

    def unlike(self):
        """Зменшити к-ть лайків на 1"""
        self.likes -= 1
        self.save()

    def check_if_liked(self, user_id):
        """Перевірити, чи користувач поставив лайк"""
        if int(user_id) in self.list_of_likers['liked']:
            return True
        else:
            return False

class BlogPost(models.Model):
    """Допис у блозі"""
    film = models.ForeignKey('Film', on_delete=models.CASCADE, verbose_name='Заголовок')
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE, default=CustomUser.objects.get(id=1).id, verbose_name='Автор')
    text = models.TextField(verbose_name='Текст')
    date_added = models.DateTimeField(auto_now_add=True, verbose_name='Дата додання')

    def __str__(self):
        return self.text[:20]

films/forms.py
from django import forms

from .models import *

class TagForm(forms.ModelForm):
    """Форма для створення тега"""
    class Meta:
        model = Tag
        fields = '__all__'
        widgets = {
            'title': forms.TextInput(attrs={'class': 'input-char'})
        }


class FilmForm(forms.ModelForm):
    """Форма для створення фільму"""
    class Meta:
        model = Film
        fields = '__all__'
        widgets = {
            'title': forms.TextInput(attrs={'class': 'input-char'}),
            'image': forms.FileInput(attrs={'class': 'input-file'}),
            'text': forms.Textarea(attrs={'id': 'add-comm-text', 'cols': 55, 'rows': 15}),
            'duration': forms.NumberInput(attrs={'class': 'input-micro'}),
            'url': forms.TextInput(attrs={'class': 'input-char'}),
            'country': forms.Select(attrs={'class': 'input-micro'}),
            'tag1': forms.Select(attrs={'class': 'input-micro'}),
            'tag2': forms.Select(attrs={'class': 'input-micro'}),
        }


class CommentForm(forms.ModelForm):
    """Форма для створення коментаря"""
    def __init__(self, *args, **kwargs):
        film_id = kwargs.pop('film_id')
        user_id = kwargs.pop('user_id')
        super().__init__(*args, **kwargs)
        self.fields['film'].initial = Film.objects.get(id=film_id)
        self.fields['author'].initial = CustomUser.objects.filter(id=user_id)[0]

    class Meta:
        model = Comment
        fields = ['film', 'title', 'text', 'author']
        widgets = {
            'film': forms.TextInput(attrs={'type': 'hidden'}),
            'author': forms.TextInput(attrs={'type': 'hidden'}),
            'title': forms.TextInput(attrs={'id': 'add-comm-title'}),
            'text': forms.Textarea(attrs={'id': 'add-comm-text', 'cols': 60, 'rows': 10}),
        }

films/views.py
import random
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required

from .models import *
from .forms import *

def index(request):
    """Головна сторінка"""
    #Бойовики
    blockbusters = []
    blockbusters_id = Tag.objects.filter(title='Бойовик')
    if blockbusters_id:
        blockbusters = Film.objects.filter(tag1=blockbusters_id[0].id) | Film.objects.filter(tag2=blockbusters_id[0].id)

    # Комедії
    comedy = []
    comedy_id = Tag.objects.filter(title='Комедія')
    if comedy_id:
        comedy = Film.objects.filter(tag1=comedy_id[0].id) | Film.objects.filter(tag2=comedy_id[0].id)

    # Фантастика
    fantastyka = []
    fantastyka_id = Tag.objects.filter(title='Фантастика')
    if fantastyka_id:
        fantastyka = Film.objects.filter(tag1=fantastyka_id[0].id) | Film.objects.filter(tag2=fantastyka_id[0].id)

    films = Film.objects.filter()
    context = {
        'films': films[:4],
        'blockbusters': blockbusters[:4],
        'comedy': comedy,
        'fantastyka': fantastyka
    }
    return render(request, 'films/index.html', context)

def more(request):
    """Показати детальнішу інформацію"""
    films = Film.objects.filter().order_by('title')
    context = {
        'films': films
    }
    return render(request, 'films/film_list.html', context)

def film(request, film_id):
    """Конкретний фільм"""
    film = get_object_or_404(Film, id=film_id)
    comments = Comment.objects.filter(film=film_id).order_by('-likes')

    #Отримати нік користувача
    user_id = None
    accuser = None
    if request.user.is_authenticated:
        user_id = request.user.id
        accuser = get_object_or_404(CustomUser, id=user_id)

    if str(request.user) == 'AnonymousUser':
        form = None
    else:
        if request.method != 'POST':
            form = CommentForm(film_id=film_id, user_id=user_id)
        else:
            form = CommentForm(request.POST, film_id=film_id, user_id=user_id)
            if form.is_valid():
                form.save()
                return redirect('films:film', film_id)

    context = {
        'film': film,
        'comments': comments,
        'form': form,
        'accuser': accuser
    }
    return render(request, 'films/chosen_film.html', context)


@login_required
def new_tag(request):
    """Додати новий тег"""
    if request.method != 'POST':
        form = TagForm()
    else:
        form = TagForm(data = request.POST)
        if form.is_valid():
            form.save()
            return redirect('films:new_tag')

    tags = Tag.objects.all().order_by('title').values()

    context = {
        'form': form,
        'tags': tags
    }
    return render(request, 'films/new_tag.html', context)


@login_required
def new_film(request):
    """Додати новий фільм"""
    if request.method != 'POST':
        form = FilmForm()
    else:
        form = FilmForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('films:new_film')

    context = {'form': form}
    return render(request, 'films/new_film.html', context)


@login_required
def add_like(request, film_id, comment_id, user_id):
    """Додати лайк"""
    comment = get_object_or_404(Comment, id=comment_id)
    if int(user_id) not in comment.list_of_likers['liked']:
        comment.list_of_likers['liked'].append(user_id)
        comment.like()
    else:
        comment.list_of_likers['liked'].remove(user_id)
        comment.unlike()
    return redirect('films:film', film_id)


def random_film(request):
    """Показати рандомний фільм"""
    films = Film.objects.all()
    last_id = len(films)
    try:
        return redirect('films:film', random.randint(1, last_id))
    except:
        return redirect('films:film', 1)


def blog(request):
    """Сторінка блогу"""
    texts = BlogPost.objects.all()
    len_texts = len(texts)
    posts = {
        'texts': texts,
        'colors': [145 + i for i in range(len_texts)],
        'ids': [i for i in range(len_texts)]
    }
    context = {
        'posts': posts
    }
    return render(request, 'films/blog.html', context)

films/templates/films/base.html
{% load static %}

{% if messages %}
    {% for message in messages %}
      <div class="alert {% if message.tags %} alert-{{ message.tags }}{% endif %}">{{ message|safe }}</div>
    {% endfor %}
  {% endif %}

  {% if form.errors %}
    <div class="alert alert-error">
      <h4>Please fix the following errors</h4>
      <ul>
        {% for field in form %}
          {% if field.errors %}
            {% for error in field.errors %}
              <li><a href="#id_{{ field.name }}" class="error">{{ error|escape }}</a></li>
            {% endfor %}
          {% endif %}
        {% endfor %}
      </ul>
      {% if form.non_field_errors %}
        {{ form.non_field_errors }}
      {% endif %}
    </div>
  {% endif %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link type="text/css" href="{% static 'films/css/style.css' %}" rel="stylesheet">
    {% block head %}

    {% endblock head %}
</head>
<body>

<style>
    body{
        background: url('{% static 'films/img/background.png' %}');
        background-attachment: fixed;
        background-size: cover;
        background-repeat: no-repeat;
    }
</style>

<header>
        <table>
            <tr>
                <td class="td-5">
                    <div class="base-header">
                        <a class="base-header" href="{% url 'films:index' %}"><img class="logo" src="{% static 'films/img/logo.png' %}"></a>
                        <a class="base-header" href="{% url 'films:more' %}">Детальніше</a>
                        <a class="base-header" href="{% url 'films:blog' %}">Блог</a>
                        <a class="base-header" href="#">Форум</a>
                        {% if user.is_authenticated %}
                            <a class="base-header" href="{% url 'films:new_tag' %}">+ тег</a>
                            <a class="base-header" href="{% url 'films:new_film' %}">+ фільм</a>
                        {% endif %}
                    </div>
                </td>
                <td class="td-5">
                    {% if user.is_authenticated %}
                        <div class="base-header-2">
                            <a class="base-header" href="{% url 'users:account' user.id %}">Моя сторінка</a>
                            <a class="base-header" href="{% url 'users:logout' %}">Вийти</a>
                        </div>
                    {% else %}
                        <div class="base-header-2">
                            <a class="base-header" href="{% url 'users:register' %}">Реєстрація</a>
                            <a class="base-header" href="{% url 'users:login' %}">Вхід</a>
                        </div>
                    {% endif %}
                </td>
            </tr>
        </table>
    </header>
    {% block content %}

    {% endblock content %}

    <footer>
        <table class="footer-content">
            <tr>
                <td>
                    <p>Що в нас тут за сайт?</p>
                    <ul>
                        <li>Нові фільми</li>
                        <li>Світова класика</li>
                        <li>Трендові серіали</li>
                        <li>Трейлери новинок</li>
                    </ul>
                </td>
                <td>&nbsp</td>
                <td>&nbsp</td>
                <td>&nbsp</td>
                <td>
                    &#169;Проект виконано в навчальних цілях,<br> посилання на джерела інформації:
                    <ul>
                        <li><a href="https://megogo.net/ua">Megogo.net</a></li>
                        <li><a href="https://www.kinofilms.ua/ukr/news/reviews/">Kinofilms.ua</a></li>
                    </ul>
                </td>
                <td>
                    <p>Навігаця сайтом</p>
                    <ul>
                        <li><a href="{% url 'films:index' %}">На головну</a></li>
                        <li><a href="{% url 'films:blog' %}">Блог</a></li>
<!--                        <li><a href="#">Випадкова категорія</a></li>-->
                        <li><a href="{% url 'films:random_film' %}">Випадковий фільм</a></li>
                    </ul>
                </td>
            </tr>
        </table>
    </footer>
</body>
</html>

films/templates/films/blog.html
{% extends 'films/base.html' %}
{% load static %}

{% block head %}
    <title>Блог</title>
{% endblock head %}


{% block content %}
<style>
    .all-posts{
    width: 80%;
    align: center;
    margin-left: 10%;
    margin-top: 5%;
    border-radius: 5px;
    border: #9E972B solid 3px;
}
</style>
    <h1 align="center">Кіно-Блог</h1>

        <ul class="post-list">
            {% for post in posts.texts %}
                <style>
                    .all-posts{
                        background: rgb(111, 111, 111);
                    }
                </style>
                <div class="all-posts">
                    <li>
                        <div class="post">
                            <p class="post-author">
                                {% if post.author.image %}
                                    <a href="{% url 'users:account' post.author.id %}"><img class="post-avatar comment-avatar comment-content" src="{{ post.author.image.url }}"></a>
                                {% else %}
                                    <a href="{% url 'users:account' post.author.id %}"><img class="post-avatar comment-avatar comment-content" src="{% static 'films/img/anon_image.png' %}"></a>
                                {% endif %}
                                <a href="{% url 'users:account' post.author.id %}">{{ post.author.username }}</a>
                            </p>
                            <div class="post-content comment-content">
                                <p class="post-text">{{ post.text }}</p>
                            </div>
                            <table>
                                <tr>
                                    <td width="83%"><p>Фільм: <a href="{% url 'films:film' post.film.id %}">{{ post.film.title }}</a></p></td>
                                    <td width="17%"><p>Опубліковано: {{ post.date_added|date:'d M Y' }}</p></td>
                                </tr>
                            </table>



                        </div>
                    </li>
                </div>

            {% endfor %}
        </ul>


{% endblock content %}

films/templates/films/chosen_film.html
{% extends 'films/base.html' %}
{% load static %}
{% load films_extras %}

{% block head %}
    <title>{{ film.title }}</title>
{% endblock head %}



{% block content %}

<style>
.like-button{
    background:  url('{% static 'films/img/like_hollow.png' %}');
    background-size: contain;
    background-repeat: no-repeat;
    width: 50px;
    height: 50px;
    background-color: transparent;
    border-color: transparent;
}


.liked:hover{
    background:  url('{% static 'films/img/like_hollow.png' %}');
    background-size: contain;
    background-repeat: no-repeat;
    cursor: pointer;
}


.unliked:hover{
    background:  url('{% static 'films/img/like.png' %}');
    background-size: contain;
    background-repeat: no-repeat;
    cursor: pointer;
}


.liked{
    background:  url('{% static 'films/img/like.png' %}');
    background-size: contain;
    background-repeat: no-repeat;
}


.unliked
    background:  url('{% static 'films/img/like_hollow.png' %}');
    background-size: contain;
    background-repeat: no-repeat;
}
</style>
    <div>
        <h1 align="center">{{ film.title }}</h1>
        <div class="film-caption">
            <table>
                <tr>
                    <td>
                        <img id="film-image-caption" src="{{ film.image.url }}">
                    </td>
                    <td>
                        <div class="film-text-caption">
                            <p>{{ film.text }}</p>
                            <hr>
                            <p>
                                {{ film.country }}
                                {{ film.tag1 }}
                                {{ film.tag2 }}
                                {{ film.duration }} хв
                            </p>
                        </div>
                    </td>
                </tr>
            </table>

        </div>
    </div>

    <div class="film-trailer-container">
        <h2 align="center">Трейлер</h2>
        <iframe class="film-trailer" width="560" height="315" src={{ film.url }} title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    </div>
    <div class="film-comments-container">
        <h2 align="center">Коментарі</h2>
        <ul>
            {% for comment in comments %}
                <li>
                    <div class="comment">
                        <p>
                            <form action="{% url 'films:add_like' film.id comment.id user.id %}">
                                {% if comment.author.image %}
                                    <a href="{% url 'users:account' comment.author.id %}"><img class="comment-avatar comment-content" src="{{ comment.author.image.url }}"></a>
                                {% else %}
                                    <img class="comment-avatar comment-content" src="{% static 'films/img/anon_image.png' %}">
                                {% endif %}
                                <a href="{% url 'users:account' comment.author.id %}">{{ comment.author }}</a>, {{ comment.date_added|date:'Y M d' }}
                                {% if comment.list_of_likers.liked|check_if_liked:user.id %}
                                    <button class="like-button liked"></button>
                                {% else %}
                                    <button class="like-button unliked"></button>
                                {% endif %}
                                {{ comment.likes }}
                            </form>
                        </p>


                        <div class="comment-content simple-shadow">
                            <p class="comment-title"><b>{{ comment.title }}</b></p>
                            <p><i>{{ comment.text }}</i></p>

                        </div>

                    </div>
                </li>
            {% empty %}
                <p>Коментарів до цього фільму ще немає.</p>
            {% endfor %}
            {% if user.is_authenticated %}
                <h3 align="center">Додати коментар</h3>

                <div class="comment-content">
                    <form action="{% url 'films:film' film.id %}" method="post">
                        {% csrf_token %}
                        {% if user.image %}
                            <a href="{% url 'users:account' user.id %}"><img class="comment-avatar comment-content shadow" src="{{ accuser.image.url }}"></a>
                            <a href="{% url 'users:account' accuser.id %}">{{ accuser.username }}</a>
                            <p>
                                {{ form.title }}
                                <button id="comment-add-button" name="submit">Опублікувати</button>
                            </p>
                        {% else %}
                            <img class="comment-avatar comment-content shadow" src="{% static 'films/img/anon_image.png' %}">
                            <a href="{% url 'users:account' accuser.id %}">{{ accuser.username }}</a>
                                <p>
                                {{ form.title }}
                                <button id="comment-add-button" name="submit">Опублікувати</button>
                            </p>
                        {% endif %}
                        <div>
                            {{ form.text }}
                            {{ form.author }}
                            {{ form.film }}
                        </div>
                    </form>
                </div>
            {% else %}
                <h3 align="center">Лише авторизовані користувачі можуть коментувати</h3>
                <p align="center"><a href="{% url 'users:login' %}"><button>Авторизуватись</button></a></p>
            {% endif %}

        </ul>
    </div>
{% endblock content %}

films/templates/films/film_list.html
{% extends 'films/base.html' %}

{% block head %}
    <title>BestFilms</title>
{% endblock head %}

{% block content %}
        {% for film in films %}
            <div class="film-container">
                <table>
                    <tr>
                        <td colspan="5"><h1 class="title">{{ film.title }}</h1></td>
                    </tr>
                    <tr>
                        <td><a href="{% url 'films:film' film.id %}"><img class="film-image" src="{{ film.image.url }}"></a></td>
                        <td colspan="4"><p class="film-caption">{{ film.text }}</p></td>
                    </tr>
                    <tr class="detail-info">
                        <td class="button-td"><a href="{% url 'films:film' film.id %}"><button class="watch-film-button">Дивитись онлайн</button></a></td>
                        <td><p class="film-info">Тривалість: {{ film.duration }}хв</p></td>
                        <td><p class="film-info">{{ film.country }}</p></td>

                        {% if film.tag1 %}
                            <td><p class="film-info">{{ film.tag1 }}</p></td>
                        {% else %}
                            <td>&nbsp;</td>
                        {% endif %}

                        {% if film.tag2 %}
                            <td><p class="film-info">{{ film.tag2 }}</p></td>
                        {% else %}
                            <td>&nbsp;</td>
                        {% endif %}
                    </tr>
                </table>







            </div>
        {% endfor %}
{% endblock content %}

films/templates/films/index.html
{% extends 'films/base.html' %}
{% load static %}

{% block head %}
    <title>BestFilms</title>
{% endblock head %}

{% block content %}
    <div class="main-content">
        <h1 class="index-title">Наші фільми</h1>
        <div class="category-title">
            <h2 class="category-title-text">Бойовики</h2>
        </div>

<!--        Поставити слайдер-->

        <table class="preview-content">
            <tr>
            {% for film in blockbusters %}
                <td>
                    <div class="film-preview">
                        <a href="{% url 'films:film' film.id %}"><img class="preview-image" src="{{ film.image.url }}"></a>
                    </div>

                </td>

            {% endfor %}
                <td>
                    <a href="#"><img class="next-icon" src="{% static 'films/img/show_more.png' %}"></a>
                </td>
            </tr>
        </table>

<!--        Кінець слайдера-->

    <div class="category-title">
        <h2 class="category-title-text">Фантастика</h2>
    </div>

<!--        Поставити слайдер-->

        <table class="preview-content">
            <tr>
            {% for film in fantastyka %}
                <td>
                    <div class="film-preview">
                        <a href="{% url 'films:film' film.id %}"><img class="preview-image" src="{{ film.image.url }}"></a>
                    </div>

                </td>

            {% endfor %}
                <td>
                    <a href="#"><img class="next-icon" src="{% static 'films/img/show_more.png' %}"></a>
                </td>
            </tr>
        </table>

<!--        Кінець слайдера-->



        <div class="category-title">
        <h2 class="category-title-text">Комедії</h2>
    </div>

<!--        Поставити слайдер-->

        <table class="preview-content">
            <tr>
            {% for film in comedy %}
                <td>
                    <div class="film-preview">
                        <a href="{% url 'films:film' film.id %}"><img class="preview-image" src="{{ film.image.url }}"></a>
                    </div>

                </td>

            {% endfor %}
                <td>
                    <a href="#"><img class="next-icon" src="{% static 'films/img/show_more.png' %}"></a>
                </td>
            </tr>
        </table>

<!--        Кінець слайдера-->


    </div>
{% endblock content %}

films/templates/films/new_film.html
{% extends 'films/base.html' %}

{% block content %}
    <h1 align="center">Додати новий фільм:</h1>

    <form action="{% url 'films:new_film' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table align="center" class="film-add-table">
            <tr>
                <td>Постер:</td><td>{{ form.image }}</td>
            </tr>
            <tr>
                <td>Назва:</td><td>{{ form.title }}</td>
            </tr>
            <tr>
                <td>Опис:</td><td>{{ form.text }}</td>
            </tr>
            <tr>
                <td>Трейлер:</td><td>{{ form.url }}</td>
            </tr>
            <tr>
                <td>Тривалість:</td><td>{{ form.duration }}</td>
            </tr>
            <tr>
                <td>Країна:</td><td>{{ form.country }}</td>
            </tr>
            <tr>
                <td>Жанр:</td><td>{{ form.tag1 }}</td>
            </tr>
            <tr>
                <td>Жанр:</td><td>{{ form.tag2 }}</td>
            </tr>
            <tr>
                <td></td><td><button id="comment-add-button" name="submit">Додати</button></td>
            </tr>
            <tr>
                <td></td><td><br></td>
            </tr>
        </table>

    </form>
{% endblock content %}

films/templates/films/new_tag.html
{% extends 'films/base.html' %}

{% block content %}
    <h1 align="center">Додати новий тег:</h1>

    <form action="{% url 'films:new_tag' %}" method="post">
        {% csrf_token %}
        <p align="center">{{ form.title }}</p>
        <p align="center"><button name="submit">Додати</button></p>
    </form>
    <div class="post-on-page simple-shadow">
        <h2 align="center">Список існуючих тегів:</h2>
        <ul>
            {% for tag in tags %}
                <li>{{ tag.title }}</li>
            {% empty %}
                <li>Додайте перший тег</li>
            {% endfor %}
        </ul>
    </div>
{% endblock content %}